[package]
name = "better-limit-reader"
version = "0.1.0"
authors = ["Michael de Silva <michael@cyberdynea.io"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
flate2 = "1.0.33"

[dev-dependencies]
tempfile = "3.12.0"